%dev.quarkus.http.port=8090
quarkus.http.port=8080
quarkus.smallrye-openapi.store-schema-directory=./
http.port=80
http.host=hackerapp.apps.cluster-b69w2.dynamic.redhatworkshops.io

quarkus.openshift.env.vars.current-ns.field=metadata.namespace
